name: Generate Pages

env:
  CI: true
  FORCE_COLOR: true

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write

jobs:
  generate-api-files:
    name: Generate API files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Node.js & Yarn
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
        env:
          # Workaround for https://github.com/actions/setup-node/issues/317
          FORCE_COLOR: 0

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Fetch API data
        run: yarn once
        env:
          UNICHAIN_RPC_URL: ${{ secrets.UNICHAIN_RPC_URL }}
          DUNE_API_KEY: ${{ secrets.DUNE_API_KEY }}
          VYUSD_PRICE: ${{ vars.VYUSD_PRICE }}
          DUNE_SPV2_AVERAGE_APY_URL: ${{ vars.DUNE_SPV2_AVERAGE_APY_URL }}
          DUNE_SPV2_UPFRONT_FEE_URL: ${{ vars.DUNE_SPV2_UPFRONT_FEE_URL }}

      - name: Commit generated files
        uses: EndBug/add-and-commit@v9
        if: ${{ github.event_name != 'pull_request' }}
        with:
          message: "chore: update generated files"
          default_author: github_actions
          add: docs
          push: --force origin HEAD:pages
